### ISSUE TITLE
Android 打包后tbs初始化false

### ISSUE THREAD

**Issue by ziyotko** [gstory0404/file_preview#1]
Android 打包后tbs初始化false

**Comment by gstory0404** [comment]
```
buildTypes {
        release {
            //关闭删除无用资源
            shrinkResources false
            //关闭删除无用代码
            minifyEnabled false
            zipAlignEnabled true
        }
    }
```
是否参考文档 做这个设置

**Comment by ziyotko** [comment]
W/ContextImpl(31678): Failed to ensure /storage/emulated/0/Android/data/com.tencent.mm/files/stable: java.lang.SecurityException: Invalid mkdirs path: /storage/emulated/0/Android/data/com.tencent.mm/files/stable
W/ContextImpl(31678): Failed to ensure /storage/emulated/0/Android/data/com.tencent.mm/files/stable: java.lang.SecurityException: Invalid mkdirs path: /storage/emulated/0/Android/data/com.tencent.mm/files/stable
直接跑的demo

**Comment by gstory0404** [comment]
手机型号、系统是多少，有换一部手机试过吗

**Comment by gstory0404** [comment]
> 

手机型号、系统是多少，有换一部手机试过吗

**Comment by ziyotko** [comment]
Nova 8 SE HarmonyOS 2.0.0

**Comment by yjt1216** [comment]
免费资源不错了
