### ISSUE TITLE
安卓可以接收回调 ios无反应 

### ISSUE THREAD

**Issue by supermebing** [gstory0404/file_preview#10]
FilePreviewCallBack(onShow: () {
            LogUtil.e("文件打开成功");
            YxtLoading.hide();
          }, onDownload: (progress) {
            LogUtil.e("下载中...$progress%");
            YxtLoading.hide();
          }, onFail: (code, msg) {
            YxtLoading.hide();
            LogUtil.e("文件打开失败 $code  $msg");
          }),

**Comment by gstory0404** [comment]
ios目前仅提供onShow回调

**Comment by makeclan** [comment]
IOS onShow也不生效

**Comment by gstory0404** [comment]
最新版本已修复 @makeclan
