### ISSUE TITLE
保存文件名问题

### ISSUE THREAD

**Issue by wuhangandroid** [gstory0404/file_preview#12]
FileUtils里的downLoadFile方法使用var filename = downloadUrl.substring(downloadUrl.lastIndexOf('/') + 1)获取文件名，我想建议能不能再加判断,因为可能存在http://xxxxxxx/xxxxxt/download?id=7ba70f76bb52474db6020db0811f21e4.mp4，如果存在多个参数，等于号和.之间可能是参数名，再加上后缀，您看可行吗

**Comment by gstory0404** [comment]
一般情况下对文件名无太大影响
