### ISSUE TITLE
TBS初始化成功，一直提示下载失败

### ISSUE THREAD

**Issue by Rn17310118925** [gstory0404/file_preview#13]
版本1.1.1
![1664008745648](https://user-images.githubusercontent.com/76022946/192088935-208f19e5-4829-428f-8199-d865a9f3f8cb.png)
文件下载失败下载失败java.net.SocketTimeoutException: failed to connect to gstory.vercel.app/2001::8079:9265 (port 443) from /240e:41d:10:811a:d014:1773:eee1:344f (port 43974) after 10000ms
I/flutter (22190): 文件打开失败 1000  下载失败java.net.SocketTimeoutException: failed to connect to gstory.vercel.app/2001::8079:9265 (port 443) from /240e:41d:10:811a:d014:1773:eee1:344f (port 43974) after 10000ms

**Comment by gstory0404** [comment]
测试文件失效 使用自己文件尝试

**Comment by Rn17310118925** [comment]
那个文件可以下载啊，没失效

**Comment by Rn17310118925** [comment]
https://gstory.vercel.app/ceshi/ceshi.docx  这个链接可以在浏览器查看，而且可以正常下载，没有问题，但是在实例里下载不成功

**Comment by gstory0404** [comment]
手机浏览器尝试是否可打开  网络问题导致

**Comment by Rn17310118925** [comment]
博主这个问题解决了是测试文件失效了，用自己的文件就可以了，谢谢啦
