### ISSUE TITLE
allocator 3.x is not supported

### ISSUE THREAD

**Issue by Rn17310118925** [gstory0404/file_preview#16]
大佬，这个好不稳定，3点的时候可以预览，但是删除软件，再次安装预览就报这个一个错，预览不了
![1666948999144](https://user-images.githubusercontent.com/76022946/198553237-f680d07b-c22c-4371-aabe-d4c24edf5246.png)
![1666948999144](https://user-images.githubusercontent.com/76022946/198553238-a0b2c9dc-92bf-41fa-8754-a57d946d7e46.png)

**Comment by Rn17310118925** [comment]
我在android底下打debug，走到TBS初始化的时候return了，好像是初始化失败了

**Comment by gstory0404** [comment]
```
await FilePreview.tbsDebug(); 
```
进入debug页面 查看信息

**Comment by Rn17310118925** [comment]
大佬，tbsDebug里面线上初始化没问题，是好的，但是调初始化就还是不行

**Comment by gstory0404** [comment]
合作方加载检测 是否ok? @Rn17310118925 

> 大佬，tbsDebug里面线上初始化没问题，是好的，但是调初始化就还是不行

**Comment by Rn17310118925** [comment]
> 
先安转后检测吗，我没安装线上内核报错为未能加载X5内核，
![89a9e1763fcae193a90ff22c80cbe91](https://user-images.githubusercontent.com/76022946/198916987-b56a3da1-8de1-406b-9a87-71c28e0fa957.jpg)

**Comment by Rn17310118925** [comment]
> 合作方加载检测 是否ok?@Rn17310118925
> 
> > 大佬，tbsDebug里面线上初始化没问题，是好的，但是调初始化就还是不行

安装线上内核成功后，合作方加载检测没有问题

**Comment by gstory0404** [comment]
```dart
  file_preview:
    git:
      url: https://github.com/gstory0404/file_preview.git
      ref: 4eca6f6c27153f450bf52b6dbe6a4bd0603351d4
```
@Rn17310118925 尝试使用git源 测试下
