### ISSUE TITLE
界面加载file 尺寸问题

### ISSUE THREAD

**Issue by yjt1216** [gstory0404/file_preview#17]
![截屏2022-12-09 09 57 59](https://user-images.githubusercontent.com/12771656/206605994-d34ae0f7-03f4-4472-a1c8-42a75cf09a99.png)

如果file尺寸高度大于给定的高度，超出的部分就无法显示

**Comment by gstory0404** [comment]
文件预览是内置有放大缩小、拖动功能，不会自动缩放至完全显示的大小

**Comment by yjt1216** [comment]
> 文件预览是内置有放大缩小、拖动功能，不会自动缩放至完全显示的大小

宽度能够拖动，但是高度就拖动不了了

**Comment by yjt1216** [comment]
是不是因为这个权限问题？

![F400BAFF-3B3A-4476-B192-A4F21901351D](https://user-images.githubusercontent.com/12771656/206607884-bd12124d-6a4b-4924-be09-feb81e1bff27.png)

**Comment by gstory0404** [comment]
预览是支持文件内容上下滚动的，可以尝试提供的测试文件链接 @yjt1216

**Comment by gstory0404** [comment]
除非预览本地文件 否则插件是不需要权限的，在线预览文件时下载的内部沙盒目录的无需权限

**Comment by yjt1216** [comment]
[promise.pdf](https://github.com/gstory0404/file_preview/files/10191223/promise.pdf)

**Comment by yjt1216** [comment]
就是这个文件pdf，我上传到服务器文件，然后在app上测试预览

**Comment by gstory0404** [comment]
未发现问题

> [promise.pdf](https://github.com/gstory0404/file_preview/files/10191223/promise.pdf)

**Comment by gstory0404** [comment]
> 是支持文件内容上下滚动的，可以尝试提

无法上下滚动 看你是如何使用的 是否与其他组件滚动冲突

**Comment by yjt1216** [comment]
> > 是支持文件内容上下滚动的，可以尝试提
> 
> 无法上下滚动 看你是如何使用的 是否与其他组件滚动冲突

我是直接套用的example 中的方法，然后换个丽娜姐

**Comment by yjt1216** [comment]
> > 是支持文件内容上下滚动的，可以尝试提
> 
> 无法上下滚动 看你是如何使用的 是否与其他组件滚动冲突

我知道了，因为example 中 bottom越界问题，所以我想用SingleChildScrollView 包裹了，所以才会导致只显示部分文档
,现在改为Expanded
