### ISSUE TITLE
安卓11无法访问data目录的问题

### ISSUE THREAD

**Issue by zhushaoxing** [gstory0404/file_preview#18]
我现在像实现pdf预览的功能。使用的插件是：file_preview 1.1.4，

初始化TBS内核的时候报错：/data 目录没有权限，这个有什么好的解决方案吗。

https://img.mukewang.com/szimg/63a1546e0995276f19020672.jpg

**Comment by gstory0404** [comment]
外部data目录是非必须权限，可以尝试开启权限尝试一下
