### ISSUE TITLE
iOS预览TXT文档乱码

### ISSUE THREAD

**Issue by zou-xian** [gstory0404/file_preview#2]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-21 at 16 47 30](https://user-images.githubusercontent.com/28732810/154919832-712b221c-5cdb-414d-9f40-495206596068.png)
请问iOS预览TXT文档乱码如何修改编码？

**Comment by gstory0404** [comment]
查看一下原txt文件的编码

**Comment by gstory0404** [comment]
> ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-21 at 16 47 30](https://user-images.githubusercontent.com/28732810/154919832-712b221c-5cdb-414d-9f40-495206596068.png) 请问iOS预览TXT文档乱码如何修改编码？

查看一下原txt文件的编码

**Comment by zou-xian** [comment]
<img width="441" alt="iShot2022-02-21 17 00 50" src="https://user-images.githubusercontent.com/28732810/154922127-42ab007b-41ad-41bb-8bed-f0140ba81785.png">
这是原txt的编码  utf-8的

**Comment by gstory0404** [comment]
```
:set
--- Options ---
  backspace=2         modelines=0         ttyfast
noendofline           modified            ttymouse=sgr
  helplang=cn         scroll=11           window=0
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
```
本地测试utf8的文本不会乱码

**Comment by jjvu-xiao** [comment]
环境 iOS 15.3.1 , 手机 iPhone SE 2 ，iPhone 8
打开文本类文件会乱码
Flutter版本 1.22.6
![github](https://user-images.githubusercontent.com/53683919/164201005-a42afd58-fc5a-4335-8b48-d4eaf7eb9d40.JPG)

**Comment by gstory0404** [comment]
```
file_preview:
   git:
      url: https://github.com/gstory0404/file_preview.git
      ref: 232038b4bdb9476917a96963b4f48ab2da9e87f3
```
@zou-xian @jjvu-xiao  使用git的代码 看下 还会乱码吗
