### ISSUE TITLE
401事件

### ISSUE THREAD

**Issue by yjt1216** [gstory0404/file_preview#20]
Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getMemoryUsage","params":{"isolateId":

**Comment by yjt1216** [comment]
![simulator_screenshot_79E3327D-3AE0-4E65-B5F6-CBCDBAEED7A0](https://user-images.githubusercontent.com/12771656/209607879-acd2cac3-a73b-489c-a853-581087334826.png)

**Comment by gstory0404** [comment]
401这个文件源问题吧 @yjt1216

**Comment by yjt1216** [comment]
http://36.152.50.211:8088/uploadfile/1672108699534移动端自动化测试新利器KRunner设计实现-陈立-快手.pdf

**Comment by yjt1216** [comment]
> 401这个文件源问题吧 @yjt1216

我是用的 这个文件  http://36.152.50.211:8088/uploadfile/1672108699534移动端自动化测试新利器KRunner设计实现-陈立-快手.pdf，上个星期五突然出现的问题

**Comment by yjt1216** [comment]
> 401这个文件源问题吧 @yjt1216

而且401这个 是将加载好的文档覆盖了，因为我创建了切换按钮被覆盖了

**Comment by gstory0404** [comment]
401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试

**Comment by yjt1216** [comment]
> 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试

嗯，我在查找，偶尔出现了一次 
[Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]

**Comment by gstory0404** [comment]
> > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> 
> 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]

https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho
与插件无关

**Comment by yjt1216** [comment]
> > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > 
> > 
> > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> 
> https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关

> > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > 
> > 
> > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> 
> https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关

为什么安卓 TBS只要安装app时不成功，就一直报104

**Comment by gstory0404** [comment]
> > > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > > 
> > > 
> > > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> > 
> > 
> > https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关
> 
> > > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > > 
> > > 
> > > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> > 
> > 
> > https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关
> 
> 为什么安卓 TBS只要安装app时不成功，就一直报104

TBS文件预览功能官方 已经放弃了维护了，独立出来一个商业化的静态库无需下载，可以联系官方

**Comment by yjt1216** [comment]
> > > > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > > > 
> > > > 
> > > > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> > > 
> > > 
> > > https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关
> > 
> > 
> > > > > 401这个错误是哪里返回的，插件本身不会显示这个提示，尝试换个文件或者使用demo提供的测试文件尝试
> > > > 
> > > > 
> > > > 嗯，我在查找，偶尔出现了一次 [Flutter console log "Failed to send request: {"jsonrpc":"2.0","id":"105","method":"getVM","params":{}}"]
> > > 
> > > 
> > > https://stackoverflow.com/questions/54079152/flutter-console-log-failed-to-send-request-jsonrpc2-0-id9354-metho 与插件无关
> > 
> > 
> > 为什么安卓 TBS只要安装app时不成功，就一直报104
> 
> TBS文件预览功能官方 已经放弃了维护了，独立出来一个商业化的静态库无需下载，可以联系官方

怎么可以实现 直接调用 TSBdebug 界面的安装内核功能呢？

**Comment by gstory0404** [comment]
TSBdebug 界面的安装内核功能，也是触发初始化时的下载方法 @yjt1216

**Comment by yjt1216** [comment]
https://static.dingtalk.com/media/lADPJwKt23zOMOjND8DNC9A_3024_4032.jpg_720x720g.jpg?renderWidth=3024&renderHeight=4032&renderOrientation=1&isLocal=0&bizType=im
我还想着 如果安装不成功，就给用户一个按钮 直接 安装线上内核

**Comment by yjt1216** [comment]
> TSBdebug 界面的安装内核功能，也是触发初始化时的下载方法 @yjt1216

关键的 这个TSBdebug 触发的初始化下载方法可以
