### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by huoshulei** [gstory0404/file_preview#22]
D/FileUtils(15701): 当前文件格式pdf
W/System.err(15701): android.content.pm.PackageManager$NameNotFoundException: com.tencent.mtt
W/System.err(15701): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:186)
W/System.err(15701): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:157)
W/System.err(15701): 	at com.tencent.tbscommon.utils.MttLoader.getBrowserInfo(TbsJavaCore:3)
W/System.err(15701): 	at com.tencent.tbs.tbsshell.partner.reader.service.b.getBrowserInfo(TbsJavaCore:1)
W/System.err(15701): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15701): 	at com.tencent.tbs.reader.ReaderService$ServiceInvoker.invoke(Unknown Source:70)
W/System.err(15701): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
W/System.err(15701): 	at $Proxy2.getBrowserInfo(Unknown Source)
W/System.err(15701): 	at com.tencent.mtt.external.reader.MttFileReaderWrapper.<init>(Unknown Source:315)
W/System.err(15701): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:56)
W/System.err(15701): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:17)
W/System.err(15701): 	at com.tencent.tbs.reader.TbsReader.openFile(TbsJavaCore:2)
W/System.err(15701): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15701): 	at com.tencent.smtt.export.external.DexLoader.invokeMethod(Unknown Source:14)
W/System.err(15701): 	at com.tencent.smtt.sdk.ReaderWizard.openFile(Unknown Source:44)
W/System.err(15701): 	at com.tencent.smtt.sdk.TbsReaderView.openFile(Unknown Source:61)
W/System.err(15701): 	at com.gstory.file_preview.FilePreview.openFile(FilePreview.kt:133)
W/System.err(15701): 	at com.gstory.file_preview.FilePreview.loadFile(FilePreview.kt:106)
W/System.err(15701): 	at com.gstory.file_preview.FilePreview.<init>(FilePreview.kt:56)
W/System.err(15701): 	at com.gstory.file_preview.FilePreviewFactory.create(FilePreviewFactory.kt:21)
W/System.err(15701): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
W/System.err(15701): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
W/System.err(15701): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
W/System.err(15701): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(15701): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(15701): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err(15701): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(15701): 	at android.os.Handler.handleCallback(Handler.java:873)
W/System.err(15701): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(15701): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(15701): 	at android.app.ActivityThread.main(ActivityThread.java:7009)
W/System.err(15701): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15701): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
W/System.err(15701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/PlatformViewsController(15701): Hosting view in view hierarchy for platform view: 0
E/libc    (15701): Access denied finding property "persist.vendor.fps.history.enabled"
W/RenderThread(15701): type=1400 audit(0.0:4602): avc: denied { map } for path="/dev/__properties__/u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=27917 scontext=u:r:untrusted_app:s0:c221,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    (15701): Access denied finding property "persist.vendor.hwui.skia.multithread.enabled"
E/libc    (15701): Access denied finding property "persist.vendor.hwui.skia.reduce.overdraw.enabled"
W/RenderThread(15701): type=1400 audit(0.0:4604): avc: denied { map } for path="/dev/__properties__/u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=27917 scontext=u:r:untrusted_app:s0:c221,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
I/flutter (15701): 文件打开成功
D/TbsPbBridge(15701): NetworkInfo_getExtraInfo  allow 
W/System.err(15701): java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tencent.tbscommon.plugin.exports.QBPluginItemInfo.mPackageSize' on a null object reference
W/System.err(15701): 	at com.tencent.tbs.tbsshell.partner.reader.service.l$a.getPackageSize(TbsJavaCore:1)
W/System.err(15701): 	at com.tencent.mtt.external.reader.internal.v.b(Unknown Source:14)
W/System.err(15701): 	at com.tencent.mtt.external.reader.internal.t.a(Unknown Source:10)
W/System.err(15701): 	at com.tencent.mtt.external.reader.internal.l.a(Unknown Source:26)
W/System.err(15701): 	at com.tencent.mtt.external.reader.internal.l$b.a(Unknown Source:194)
W/System.err(15701): 	at com.tencent.mtt.external.reader.a.p$c.handleMessage(Unknown Source:11)
W/System.err(15701): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(15701): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(15701): 	at android.app.ActivityThread.main(ActivityThread.java:7009)
W/System.err(15701): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15701): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
W/System.err(15701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by gstory0404** [comment]
X5内核的TBS稳定性较差，可以尝试使用v2的付费的离线TBS服务

**Comment by yjt1216** [comment]
> X5内核的TBS稳定性较差，可以尝试使用v2的付费的离线TBS服务

v2付费？稳定性如何？

**Comment by yjt1216** [comment]
看过了 三个月500块

**Comment by gstory0404** [comment]
> > X5内核的TBS稳定性较差，可以尝试使用v2的付费的离线TBS服务
> 
> v2付费？稳定性如何？

稳定性 我这边使用的测试key.离线sdk 文件基本没出现过失败
