### ISSUE TITLE
V2sdk版本是否可以升级到最新 

### ISSUE THREAD

**Issue by supermebing** [gstory0404/file_preview#24]
V2sdk版本是否可以升级到最新 TbsFileSdk_base_arm64_release_1.0.5.6000017.20230423093653.aar

**Comment by gstory0404** [comment]
后续会更新个版本v2合并到插件主仓库中，并且sdk会更新至最新

**Comment by supermebing** [comment]
我提交了个pr先临时改下了 修复了一些设备和安卓 12 13的兼容性

**Comment by gstory0404** [comment]
已合并
