### ISSUE TITLE
1.1.6

### ISSUE THREAD

**Issue by lumianchan** [gstory0404/file_preview#26]
文件路径/data/user/0/com.zxt.task.zxt_task/cache/customCacheKey/205e12e0-e348-11ed-b1c0-5515c92e03f9.doc 
提示文件打开失败！文件格式暂不支持

**Comment by gstory0404** [comment]
https://gstory.vercel.app/ceshi/ceshi.doc
本地/在线测试正常
导出文件查看文件是否损坏 @lumianchan

**Comment by oopuuu** [comment]
> 文件路径/data/user/0/com.zxt.task.zxt_task/cache/customCacheKey/205e12e0-e348-11ed-b1c0-5515c92e03f9.doc
> 提示文件打开失败！文件格式暂不支持

是不是因为免费版的停止服务了？我最近也是这样的提示

**Comment by gstory0404** [comment]
https://github.com/gstory0404/file_preview/blob/master/CHANGELOG.md
v1.1.6已切换至新的付费内核，需要新的初始化方法处理。本地测试文件均正常，文件是否方便提供下测试？

> > 文件路径/data/user/0/com.zxt.task.zxt_task/cache/customCacheKey/205e12e0-e348-11ed-b1c0-5515c92e03f9.doc
> > 提示文件打开失败！文件格式暂不支持
> 
> 是不是因为免费版的停止服务了？我最近也是这样的提示

**Comment by 1129802827** [comment]
你好, 升级到 1.1.6 之后 initTBS 需要传一个 license, 请问这个 license 是什么,要去哪里获取

**Comment by gstory0404** [comment]
> 你好, 升级到 1.1.6 之后 initTBS 需要传一个 license, 请问这个 license 是什么,要去哪里获取

X5内核的TBS预览服务已经不能使用了，现在接入的是新的付费sdk 需要去https://cloud.tencent.com/product/tbs  申请一个license

**Comment by 1129802827** [comment]
好的,谢谢您~
