### ISSUE TITLE
下载失败java.net.SocketTimeoutException: SSL handshake timed out

### ISSUE THREAD

**Issue by Brislis** [gstory0404/file_preview#29]
### 描述
> 异常/需求具体描述
示例里的文件全部下载失败，但是在电脑浏览器能正常下载，我自己的文件能正常下载（我的文件为地址为Http协议），但是打不开（可能跟安装未知来源应用权限有关系），显示不支持该类型，但是是个正常未损坏的文件
### 设备版本
> 本地flutter版本、设备型号版本
flutter版本：2.8.0，设备坚果Pro2
### 插件版本
> 插件版本号
插件版本：  file_preview:
    git:
      url: https://github.com/gstory0404/file_preview.git
      ref: v1

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
可能是vercel的问题 测试文件是放到vercel上的
