### ISSUE TITLE
pdf无法打开

### ISSUE THREAD

**Issue by ichenwanbing** [gstory0404/file_preview#33]
### 描述
> 异常/需求具体描述
java.lang.Class<com.tencent.pdfium.PDFium>: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.orginone/app_tbs/home/default/components/file/6000017/libmttpdfcore.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
### 设备版本
> 本地flutter版本、设备型号版本
flutter 3.7.0
安卓模拟器
### 插件版本
> 插件版本号
1.1.6
### 日志
> 详细的log日志或者截图录屏
```
java.lang.Class<com.tencent.pdfium.PDFium>: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.orginone/app_tbs/home/default/components/file/6000017/libmttpdfcore.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
![image](https://github.com/gstory0404/file_preview/assets/18181880/fad55320-a390-4fb6-8fc3-b8f03116dbdd)
![image](https://github.com/gstory0404/file_preview/assets/18181880/c93e48b0-77c2-481e-864c-57465a7992f8)
疯狂打印日志，退出页面日志消失
```

**Comment by gstory0404** [comment]
看起来不支持x86，模拟器不能用，尝试使用真机

**Comment by ichenwanbing** [comment]
好的，谢谢回复



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月20日 09:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gstory0404/file_preview] pdf无法打开 (Issue #33) |

看起来不支持x86，模拟器不能用，尝试使用真机
