### ISSUE TITLE
ios端报错

### ISSUE THREAD

**Issue by zyf540860996** [gstory0404/file_preview#37]
### 描述
IOS报错

### 设备版本
> flutter 3.16.0 / dart 3.2.0 / ios 16.7.2 

### 插件版本
> file_preview 1.1.8

### 日志
> 详细的log日志或者截图录屏
```
<img width="1205" alt="image" src="https://github.com/gstory0404/file_preview/assets/10524382/d43ad31b-7d26-4b14-ba39-63bb23309b20">

```

**Comment by zyf540860996** [comment]
Swift/arm64-apple-ios.swiftinterface:34403: Fatal error: Float value cannot be converted to Int because it is either infinite or NaN
Swift/arm64-apple-ios.swiftinterface:34403: Fatal error: Float value cannot be converted to Int because it is either infinite or NaN
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Float value cannot be converted to Int because it is either infinite or NaN
    frame #0: 0x00000001877c8818 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1877c8818 <+0>: ret    
libswiftCore.dylib`:
    0x1877c881c <+0>: b      0x1877c8818               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1877c8820 <+0>: adrp   x8, 376361
    0x1877c8824 <+4>: ldrb   w0, [x8, #0x434]
Target 0: (Runner) stopped.

**Comment by gstory0404** [comment]
widget宽高设置整数 试一下

**Comment by zyf540860996** [comment]
宽高的问题
