### ISSUE TITLE
制定宽和高, 太low了吧

### ISSUE THREAD

**Issue by yanashenyang** [gstory0404/file_preview#38]
### 描述
> 异常/需求具体描述

### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
flutter中加载原生view需要用到AndroidView、UiKitView。加载他们需要指定一个大小的容器
怎么指定这个宽高才不算low呢？

**Comment by yanashenyang** [comment]
> flutter中加载原生view需要用到AndroidView、UiKitView。加载他们需要指定一个大小的容器 怎么指定这个宽高才不算low呢？

可不可以先拿到父级的约束大小, 再传递给原生的view. 这样子可以不

**Comment by gstory0404** [comment]
后续更新可以加入进去

**Comment by yanashenyang** [comment]
大佬666
