### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by zhaohuanhui** [gstory0404/file_preview#4]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_screenutil-5.3.1/lib/screenutil_init.dart:23:54: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window),
                                                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
lib/modules/study/video_learning/video_learning_controller.dart:42:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/modules/study/video_learning/video_learning_controller.dart:130:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this); //�?�?
                   ^
lib/modules/study/video_learning/components/body.dart:377:17: Error: The method 'OutlineButton' isn't defined for the class 'Body'.
 - 'Body' is from 'package:newjjclound_flutter/modules/study/video_learning/components/body.dart' ('lib/modules/study/video_learning/components/body.dart').
Try correcting the name to the name of an existing method, or defining a method named 'OutlineButton'.
                OutlineButton(
                ^^^^^^^^^^^^^
lib/modules/study/video_learning/components/body.dart:396:17: Error: The method 'OutlineButton' isn't defined for the class 'Body'.
 - 'Body' is from 'package:newjjclound_flutter/modules/study/video_learning/components/body.dart' ('lib/modules/study/video_learning/components/body.dart').
Try correcting the name to the name of an existing method, or defining a method named 'OutlineButton'.
                OutlineButton(
                ^^^^^^^^^^^^^
lib/modules/study/video_learning/components/body.dart:437:13: Error: The method 'OutlineButton' isn't defined for the class 'Body'.
 - 'Body' is from 'package:newjjclound_flutter/modules/study/video_learning/components/body.dart' ('lib/modules/study/video_learning/components/body.dart').
Try correcting the name to the name of an existing method, or defining a method named 'OutlineButton'.
            OutlineButton(
            ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/percent_indicator-3.4.0/lib/linear_percent_indicator.dart:156:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
lib/common/utils/util_tools.dart:210:30: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      locale: WidgetsBinding.instance!.window.locale,
                             ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/grouped_list-4.2.0/lib/grouped_list.dart:264:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/refresher.dart:293:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/header.dart:235:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:200:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                             ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:203:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:675:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:718:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:721:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:766:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!
                             ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:774:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:788:32: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
              SchedulerBinding.instance!
                               ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/footer.dart:244:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:198:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                             ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:201:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:596:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:663:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:705:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:708:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:751:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!
                             ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:759:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:770:32: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
              SchedulerBinding.instance!
                               ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swipe_action_cell-2.2.0/lib/core/cell.dart:1053:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swipe_action_cell-2.2.0/lib/core/cell.dart:1061:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swiper_null_safety-1.0.2/lib/src/custom_layout.dart:32:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback(_getSize);
                   ^
lib/modules/main_nav/learning_space/child_page/course/components/cupertino_listview/cupertino_listview_widget.dart:191:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback(_refreshFirstTime);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/chart/base/chart_base.dart:1792:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/chart/base/chart_base.dart:1801:28: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance?.addPostFrameCallback((_) => _refresh());
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/circular_chart/base/circular_base.dart:947:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/circular_chart/base/circular_base.dart:961:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/funnel_chart/base/funnel_base.dart:719:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/funnel_chart/base/funnel_base.dart:731:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/pyramid_chart/base/pyramid_base.dart:712:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-19.4.55/lib/src/pyramid_chart/base/pyramid_base.dart:723:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swipe_action_cell-2.2.0/lib/core/swipe_pull_align_button.dart:59:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swipe_action_cell-2.2.0/lib/core/swipe_pull_button.dart:68:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swiper_null_safety-1.0.2/lib/src/transformer_page_view/transformer_page_view.dart:516:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback(_onGetSize);
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_swiper_null_safety-1.0.2/lib/src/transformer_page_view/transformer_page_view.dart:533:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback(_onGetSize);
                     ^
../../AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/syncfusion_flutter_core-19.4.55/lib/src/legend/legend.dart:548:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!.addPostFrameCallback(
                             ^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by gstory0404** [comment]
flutte clean
flutter pub get
再运行试一下
