### ISSUE TITLE
请问tbssdk:44226   还可以下载到tbs吗?  提示-134

### ISSUE THREAD

**Issue by LiMingFei56** [gstory0404/file_preview#40]
### 描述
> 请问tbssdk:44226   还可以下载到tbs吗?  提示-134

### 插件版本
> V1      file_preview-1.1.4

### 日志
> 下载结束 状态码-134
    内核初始化完成，可能为系统内核，也可能为系统内核 
    onViewInitFinished: 是否启TBS内核false

**Comment by gstory0404** [comment]
官方已停止维护，无法下载了
