### ISSUE TITLE
下载TBS经常失败？

### ISSUE THREAD

**Issue by littlelioncjt** [gstory0404/file_preview#5]
这句代码await FilePreview.initTBS(); 很多时候会一直等待，下载不下来，只有重启应用数次偶尔才会成功。
这是怎么回事，求告知

**Comment by gstory0404** [comment]
TBS的服务下载不是很稳定

**Comment by littlelioncjt** [comment]
> TBS的服务下载不是很稳定

哥们，有什么解决办法或者其他方式预览word等文件吗？

**Comment by gstory0404** [comment]
更新一下插件试一下 还会不会失败

**Comment by gstory0404** [comment]
https://docs.qq.com/doc/DYW9QdXJNWFZnbVdz
如何还是加载失败 参考这个文档排查

**Comment by littlelioncjt** [comment]
> 更新一下插件试一下 还会不会失败

你好，我更新了现在项目run会报错了。具体如图：
![image](https://user-images.githubusercontent.com/36179203/163117779-afca0d69-20c0-4783-acb0-cc5d5a83e25d.png)

**Comment by gstory0404** [comment]
去掉阿里镜像 试一下

**Comment by littlelioncjt** [comment]
> 去掉阿里镜像 试一下

是我build.gradle配置的老阿里镜像地址的问题。版本更新后tbs也许还会存在下载失败问题，后续测试中再看下，不过感谢百忙之中回复

**Comment by littlelioncjt** [comment]
> https://docs.qq.com/doc/DYW9QdXJNWFZnbVdz 如何还是加载失败 参考这个文档排查

调试发现经常返回110错误码？
![image](https://user-images.githubusercontent.com/36179203/163152401-6f8fddde-9352-4688-b352-b1b24d99067e.png)

debugtbs.qq.com 这个网址用浏览器或者应用内嵌网页打不开，只能QQ打开，我并不懂文档说的这个。

请教下具体怎么操作？。

**Comment by gstory0404** [comment]
这个链接用TBS内核的webview
mWebView: com.tencent.smtt.sdk.WebView
WebChromeClient: com.tencent.smtt.sdk.WebChromeClient
组件打开，普通的webview是不行的

**Comment by littlelioncjt** [comment]
> 这个链接用TBS内核的webview mWebView: com.tencent.smtt.sdk.WebView WebChromeClient: com.tencent.smtt.sdk.WebChromeClient 组件打开，普通的webview是不行的

有没有机会优化下这个下载经常失败的问题呀？如图这个，我就是经常遇到这个问题，只要下载失败后续不可能再下载成功...
![image](https://user-images.githubusercontent.com/36179203/163168505-ea19b2ec-1a84-4746-a648-5cd826c5703a.png)

https://blog.csdn.net/heshuyu123/article/details/112198119
这篇文章提到过这个问题，也提供了解决方案，不知道是否有用

**Comment by gstory0404** [comment]
有做这个处理

**Comment by gstory0404** [comment]
我这边几台手机 初始化都没有问题。推荐看文档使用application中初始化方案。不然 X5内核30多M 需要一定时间
