### ISSUE TITLE
报错无法显示

### ISSUE THREAD

**Issue by songsongtao** [gstory0404/file_preview#7]
android.content.pm.PackageManager$NameNotFoundException: com.tencent.mtt
W/System.err(13275): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:243)
W/System.err(13275): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:215)
W/System.err(13275): 	at com.tencent.common.utils.MttLoader.getBrowserInfo(TbsJavaCore:380)
W/System.err(13275): 	at com.tencent.tbs.tbsshell.partner.reader.service.b.getBrowserInfo(TbsJavaCore:48)
W/System.err(13275): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(13275): 	at com.tencent.tbs.reader.ReaderService$ServiceInvoker.invoke(Unknown Source:70)
W/System.err(13275): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
W/System.err(13275): 	at $Proxy3.getBrowserInfo(Unknown Source)
W/System.err(13275): 	at com.tencent.mtt.external.reader.MttFileReaderWrapper.<init>(Unknown Source:319)
W/System.err(13275): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:422)
W/System.err(13275): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:133)
W/System.err(13275): 	at com.tencent.tbs.reader.TbsReader.openFile(TbsJavaCore:103)
W/System.err(13275): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(13275): 	at com.tencent.smtt.export.external.DexLoader.invokeMethod(Unknown Source:14)
W/System.err(13275): 	at com.tencent.smtt.sdk.ReaderWizard.openFile(Unknown Source:44)
W/System.err(13275): 	at com.tencent.smtt.sdk.TbsReaderView.openFile(Unknown Source:61)
W/System.err(13275): 	at com.gstory.file_preview.FilePreview.openFile(FilePreview.kt:127)
W/System.err(13275): 	at com.gstory.file_preview.FilePreview.loadFile(FilePreview.kt:99)
W/System.err(13275): 	at com.gstory.file_preview.FilePreview.<init>(FilePreview.kt:58)
W/System.err(13275): 	at com.gstory.file_preview.FilePreviewFactory.create(FilePreviewFactory.kt:21)
W/System.err(13275): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:185)
W/System.err(13275): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:453)
W/System.err(13275): 	at android.app.Dialog.show(Dialog.java:334)
W/System.err(13275): 	at android.app.Presentation.show(Presentation.java:279)
W/System.err(13275): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
W/System.err(13275): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
W/System.err(13275): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:214)
W/System.err(13275): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
W/System.err(13275): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
W/System.err(13275): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(13275): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
W/System.err(13275): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
W/System.err(13275): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(13275): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(13275): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(13275): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err(13275): 	at android.os.Looper.loop(Looper.java:299)
W/System.err(13275): 	at android.app.ActivityThread.main(ActivityThread.java:8291)
W/System.err(13275): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(13275): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/System.err(13275): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by songsongtao** [comment]
提示安装完成，但是无法打开

**Comment by gstory0404** [comment]
调用tbsHasInit方法 查看是否初始化完成，有时候下载完成并未安装成功会使用系统内核 而不是TBS内核 导致问题无法打开
```
//x5內核初始化完成的回调，为true表示x5内核加载成功，否则表示x5内核加载失败，会自动切换到系统内核。
Log.e("TBS内核", "onViewInitFinished:$arg0")
```
观察这个日志

**Comment by songsongtao** [comment]
2022-07-08 11:40:11.189 28472-28728/com.dj71.gtlm.gyt W/FileUtils: Failed to chmod(/data/user/0/com.tencent.mm/app_tbs): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
2022-07-08 11:40:11.189 28472-28728/com.dj71.gtlm.gyt W/FileUtils: Failed to chmod(/data/user/0/com.tencent.mm/app_tbs_common_share): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err: java.io.FileNotFoundException: /data/user/0/com.dj71.gtlm.gyt/cache/optlist.ser: open failed: ENOENT (No such file or directory)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:575)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:160)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:115)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at com.tencent.smtt.net.a.a(TbsJavaCore:63)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at com.tencent.smtt.net.a.c(TbsJavaCore:203)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at com.tencent.smtt.net.NetworkSmttService.preconnectMainResources(TbsJavaCore:131)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.Linux.open(Native Method)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8166)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:561)
2022-07-08 11:40:11.292 28472-28755/com.dj71.gtlm.gyt W/System.err: 	... 5 more
2022-07-08 11:40:11.301 28472-28472/com.dj71.gtlm.gyt E/TBS内核: onViewInitFinished:true
2022-07-08 11:40:11.301 28472-28472/com.dj71.gtlm.gyt E/TBS内核: initFinish:true
的确是加载成功了

**Comment by gstory0404** [comment]
无法加载文件？ @songsongtao

**Comment by songsongtao** [comment]
对，内核能下载成功，加载文件失败

**Comment by gstory0404** [comment]
有日志或者截图吗

> 对，内核能下载成功，加载文件失败

**Comment by songsongtao** [comment]
W/System  (31264): A resource failed to call close. 
W/FileUtils(31264): Failed to chmod(/data/user/0/com.tencent.mm/app_tbs_64): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
D/CrashReport(31264): checkServerTrusted
D/CrashReport(31264): checkServerTrusted
E/TBS内核(31264): 下载进度 16
E/TBS内核(31264): 下载进度 36
E/TBS内核(31264): 下载进度 56
E/TBS内核(31264): 下载进度 77
E/TBS内核(31264): 下载进度 96
W/System  (31264): A resource failed to call release. 
I/BpBinder(31264): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
E/TBS内核(31264): 下载完成100
E/TBS内核(31264): 安装完成

**Comment by songsongtao** [comment]
java.io.FileNotFoundException: /data/user/0/com.dj71.gtlm.gyt/cache/optlist.ser: open failed: ENOENT (No such file or directory)
W/System.err( 2122): 	at libcore.io.IoBridge.open(IoBridge.java:575)
W/System.err( 2122): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err( 2122): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
W/System.err( 2122): 	at com.tencent.smtt.net.a.a(TbsJavaCore:63)
W/System.err( 2122): 	at com.tencent.smtt.net.a.c(TbsJavaCore:203)
W/System.err( 2122): 	at com.tencent.smtt.net.NetworkSmttService.preconnectMainResources(TbsJavaCore:131)
W/System.err( 2122): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err( 2122): 	at libcore.io.Linux.open(Native Method)
W/System.err( 2122): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/System.err( 2122): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
W/System.err( 2122): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/System.err( 2122): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8166)
W/System.err( 2122): 	at libcore.io.IoBridge.open(IoBridge.java:561)
W/System.err( 2122): 	... 5 more
E/TBS内核( 2122): onViewInitFinished:true
E/TBS内核( 2122): initFinish:true

**Comment by songsongtao** [comment]
当前文件格式是pdf
W/UnsafeUtil( 2122): platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: sun.misc.Unsafe.copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
W/System.err( 2122): android.content.pm.PackageManager$NameNotFoundException: com.tencent.mtt
W/System.err( 2122): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:243)
W/System.err( 2122): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:215)
W/System.err( 2122): 	at com.tencent.common.utils.MttLoader.getBrowserInfo(TbsJavaCore:380)
W/System.err( 2122): 	at com.tencent.tbs.tbsshell.partner.reader.service.b.getBrowserInfo(TbsJavaCore:48)
W/System.err( 2122): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2122): 	at com.tencent.tbs.reader.ReaderService$ServiceInvoker.invoke(Unknown Source:70)
W/System.err( 2122): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
W/System.err( 2122): 	at $Proxy3.getBrowserInfo(Unknown Source)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.MttFileReaderWrapper.<init>(Unknown Source:319)
W/System.err( 2122): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:422)
W/System.err( 2122): 	at com.tencent.tbs.tbsshell.partner.reader.e.a(TbsJavaCore:133)
W/System.err( 2122): 	at com.tencent.tbs.reader.TbsReader.openFile(TbsJavaCore:103)
W/System.err( 2122): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2122): 	at com.tencent.smtt.export.external.DexLoader.invokeMethod(Unknown Source:14)
W/System.err( 2122): 	at com.tencent.smtt.sdk.ReaderWizard.openFile(Unknown Source:44)
W/System.err( 2122): 	at com.tencent.smtt.sdk.TbsReaderView.openFile(Unknown Source:61)
W/System.err( 2122): 	at com.gstory.file_preview.FilePreview.openFile(FilePreview.kt:132)
W/System.err( 2122): 	at com.gstory.file_preview.FilePreview.loadFile(FilePreview.kt:99)
W/System.err( 2122): 	at com.gstory.file_preview.FilePreview.<init>(FilePreview.kt:58)
W/System.err( 2122): 	at com.gstory.file_preview.FilePreviewFactory.create(FilePreviewFactory.kt:21)
W/System.err( 2122): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:185)
W/System.err( 2122): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:453)
W/System.err( 2122): 	at android.app.Dialog.show(Dialog.java:334)
W/System.err( 2122): 	at android.app.Presentation.show(Presentation.java:279)
W/System.err( 2122): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
W/System.err( 2122): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
W/System.err( 2122): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:214)
W/System.err( 2122): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
W/System.err( 2122): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
W/System.err( 2122): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err( 2122): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
W/System.err( 2122): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
W/System.err( 2122): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err( 2122): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err( 2122): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 2122): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err( 2122): 	at android.os.Looper.loop(Looper.java:299)
W/System.err( 2122): 	at android.app.ActivityThread.main(ActivityThread.java:8291)
W/System.err( 2122): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2122): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/System.err( 2122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
W/m.dj71.gtlm.gy( 2122): Accessing hidden method Landroid/app/ActivityThread;->currentProcessName()Ljava/lang/String; (unsupported, reflection, allowed)
D/IS_CTS_MODE( 2122): false

**Comment by songsongtao** [comment]
A resource failed to call close. 
W/System.err( 2122): java.nio.channels.ClosedChannelException
W/System.err( 2122): 	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:58)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginServiceImpl.b(TbsJavaCore:3600)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginServiceImpl.installPlugin(TbsJavaCore:1655)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.i.a(TbsJavaCore:370)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem.a(TbsJavaCore:647)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem.a(TbsJavaCore:969)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem$2.handleMessage(TbsJavaCore:1731)
W/System.err( 2122): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 2122): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err( 2122): 	at android.os.Looper.loop(Looper.java:299)
W/System.err( 2122): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err( 2122): java.lang.SecurityException: com.dj71.gtlm.gyt was not granted  this permission: android.permission.WRITE_SETTINGS.
W/System.err( 2122): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
W/System.err( 2122): 	at android.os.Parcel.createException(Parcel.java:2409)
W/System.err( 2122): 	at android.os.Parcel.readException(Parcel.java:2392)
W/System.err( 2122): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
W/System.err( 2122): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
W/System.err( 2122): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
W/System.err( 2122): 	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:2820)
W/System.err( 2122): 	at android.provider.Settings$System.putStringForUser(Settings.java:3525)
W/System.err( 2122): 	at android.provider.Settings$System.putStringForUser(Settings.java:3509)
W/System.err( 2122): 	at android.provider.Settings$System.putIntForUser(Settings.java:3634)
W/System.err( 2122): 	at android.provider.Settings$System.putInt(Settings.java:3627)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.internal.x.a(Unknown Source:29)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.internal.x.<init>(Unknown Source:32)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.l.a(Unknown Source:10)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.k.b(Unknown Source:97)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.r.b(Unknown Source:0)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.h.a(Unknown Source:185)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.i.b(Unknown Source:54)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.i.a(Unknown Source:40)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.g$1.a(Unknown Source:84)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.internal.l.a(Unknown Source:126)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.internal.l$2.a(Unknown Source:240)
W/System.err( 2122): 	at com.tencent.mtt.external.reader.a.p$2.handleMessage(Unknown Source:17)
W/System.err( 2122): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 2122): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err( 2122): 	at android.os.Looper.loop(Looper.java:299)
W/System.err( 2122): 	at android.app.ActivityThread.main(ActivityThread.java:8291)
W/System.err( 2122): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2122): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/System.err( 2122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
W/System.err( 2122): Caused by: android.os.RemoteException: Remote stack trace:
W/System.err( 2122): 	at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:17072)
W/System.err( 2122): 	at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:16960)
W/System.err( 2122): 	at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1866)
W/System.err( 2122): 	at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1832)
W/System.err( 2122): 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:468)
W/com.tencent.mm:appbrand1( 2122): type=1400 audit(0.0:1489049): avc: granted { execute } for comm=504446576F726B5468726561642023 path="/data/user/0/com.dj71.gtlm.gyt/app_tbs/share/plugins/com.tencent.qb.plugin.pdf/libmupdf.so" dev="dm-10" ino=1704102 scontext=u:r:untrusted_app_29:s0:c175,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c175,c258,c512,c768 tclass=file app=com.tencent.mm
W/libmupdf( 2122): closepath with no current point
W/libmupdf( 2122): closepath with no current point
I/OpenGLRenderer( 2122): Davey! duration=9222179338321ms; Flags=0, FrameTimelineVsyncId=67071741, IntendedVsync=1192698533414111, Vsync=1192698533414111, InputEventId=0, HandleInputStart=1192698533852717, AnimationStart=1192698533856415, PerformTraversalsStart=1192698533859904, DrawStart=1192698534195529, FrameDeadline=1192698550636333, FrameInterval=1192698533824071, FrameStartTime=11111111, SyncQueued=1192698534943133, SyncStart=1192698535010060, IssueDrawCommandsStart=1192698535095737, SwapBuffers=1192698549330373, FrameCompleted=9223372036854775807, DequeueBufferDuration=14896, QueueBufferDuration=905990, GpuCompleted=9223372036854775807, SwapBuffersCompleted=1192698550668237, DisplayPresentTime=0, 
W/System.err( 2122): java.nio.channels.ClosedChannelException
W/System.err( 2122): 	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:58)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginServiceImpl.b(TbsJavaCore:3600)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginServiceImpl.installPlugin(TbsJavaCore:1655)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.i.a(TbsJavaCore:370)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem.a(TbsJavaCore:647)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem.a(TbsJavaCore:969)
W/System.err( 2122): 	at com.tencent.common.plugin.impl.QBPluginSystem$2.handleMessage(TbsJavaCore:1731)
W/System.err( 2122): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 2122): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err( 2122): 	at android.os.Looper.loop(Looper.java:299)
W/System.err( 2122): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by gstory0404** [comment]
开启文件读写权限 试一下 @songsongtao

**Comment by songsongtao** [comment]
@gstory0404 权限都给了的，都能选文件了

**Comment by gstory0404** [comment]
页面显示什么

> @gstory0404 权限都给了的，都能选文件了

**Comment by songsongtao** [comment]
空白

**Comment by gstory0404** [comment]
> 空白

在线文件、本地文件均不能预览吗

**Comment by songsongtao** [comment]
@gstory0404 都不能，心态崩了

**Comment by songsongtao** [comment]
20): WebCoreClassLoader - loadClass(com.tencent.mtt.external.reader.IReaderPurchaseView,false)...
W/System.err( 1320): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/mtt/external/reader/IReaderPurchaseView;
W/System.err( 1320): 	at com.tencent.mttreader.ReaderController.setViewSize(SourceFile:474)
W/System.err( 1320): 	at com.tencent.mttreader.MTTReader.openBook(SourceFile:291)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.h.d(Unknown Source:43)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.i.d(Unknown Source:28)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.i.b(Unknown Source:128)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.i.a(Unknown Source:40)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.g$1.a(Unknown Source:84)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.internal.l.a(Unknown Source:126)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.internal.l$2.a(Unknown Source:240)
W/System.err( 1320): 	at com.tencent.mtt.external.reader.a.p$2.handleMessage(Unknown Source:17)
W/System.err( 1320): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 1320): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err( 1320): 	at android.os.Looper.loop(Looper.java:299)
W/System.err( 1320): 	at android.app.ActivityThread.main(ActivityThread.java:8291)
W/System.err( 1320): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/System.err( 1320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
W/System.err( 1320): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mtt.external.reader.IReaderPurchaseView" on path: DexPathList[[zip file "/data/user/0/com.dj71.gtlm.gyt/app_tbs/share/plugins/com.tencent.qb.plugin.txt/mttreader.jar"],nativeLibraryDirectories=[/data/user/0/com.dj71.gtlm.gyt/app_tbs/share/plugins/com.tencent.qb.plugin.txt, /system/lib64, /system_ext/lib64]]
W/System.err( 1320): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
W/System.err( 1320): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err( 1320): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)


重新下了个内核，包找不到了，deubg模式

**Comment by gstory0404** [comment]
我这边测试加载均正常，你手机型号 版本多少，换台设备试试
