### ISSUE TITLE
TBS 下载成功 初始化一直失败 

### ISSUE THREAD

**Issue by Invincible1996** [gstory0404/file_preview#9]
![image](https://user-images.githubusercontent.com/22675676/179381350-57db0f37-3fb1-4ab1-846f-66e19ca4acbb.png)

**Comment by gstory0404** [comment]
https://docs.qq.com/doc/DYW9QdXJNWFZnbVdz

4、本地无内核可用，且TbsListener.onDownLoadFinished()返回错误码 110 ？
该情况在本地无内核时，大概率命中了流控，可通过debugtbs.qq.com手动安装线上内核。

**Comment by yjt1216** [comment]
E/TBS内核(19444): 下载结束 状态码-104

**Comment by gstory0404** [comment]
可以尝试新版离线sdk 不许下载，不过需要付费
